site_name: PLaTon
site_author: C. Callé, M. Cisse, Q. Coumes, D. Revuz et al.
repo_url: https://github.com/PremierLangage/PLaTon-doc
edit_uri: tree/master/docs

nav:
- Présentation de PLaTon: 'presentation.md'
- Utiliser PLaTon: 'user_teacher.md'
- Création d'exercices: 'create_exercises.md'
- Tutoriels Thématiques: 'tutoriels_thematiques.md'
- Documentations techniques spécifiques: 'documentations_techniques.md'
- Index des clés et Lexique: 'lexique.md'

theme: readthedocs

markdown_extensions:
  - footnotes
  - admonition
