site_name: PLaTon
site_author: C. Callé, M. Cisse, Q. Coumes, D. Revuz et al.
repo_url: https://github.com/PremierLangage/PLaTon-doc
edit_uri: tree/master/docs

nav:
- Présentation de PLaTon: 'presentation/index.md'
- Utiliser PLaTon: 'use_platon/index.md'
- Création d'exercices: 'create_exo/index.md'
- Modèles d'exercices: 'models/index.md'
- Tutoriels Thématiques: 'thematic_tut/index.md'
- Documentations techniques spécifiques: 'documentations_techniques.md'
- Index des clés et Lexique: 'lexique.md'

theme: readthedocs

markdown_extensions:
  - footnotes
  - admonition
