site_name: PLaTon
site_author: C. Callé, M. Cisse, Q. Coumes, D. Revuz et al.
repo_url: https://github.com/PremierLangage/PLaTon-doc
edit_uri: tree/master/docs

nav:
- Bienvenue: 'index.md'
- Présentation de PLaTon: 'presentation/index.md'
- Utiliser PLaTon: 'use_platon/index.md'
- Création d'exercices: 'create_exo/index.md'
- Modèles d'exercices: 'models/index.md'
- Outils: 'utils/index.md'
- Tutoriels Thématiques: 'thematic_tut/index.md'
- Documentations techniques spécifiques: 'technic_doc/index.md'
- Lexique: 'lexique.md'

theme: readthedocs

markdown_extensions:
  - footnotes
  - admonition
  - wikilinks:
      base_url: 'https://documentationpl.readthedocs.io/fr/latest/lexique/#'
      end_url: ''
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: '&copy; Copyright 2016-2020 The PLaTon devs and users community'
